name: playadelcarmencondos.com.mx
favicon: null
layout_spectrum: 0.9471937322523445
typography_spectrum: 0.23797210888005793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5220937896519899
  lightness: 0.02446701587177813
  saturation: 0.10021940525621176
  rhythmicContrast: 0.04307257570326328
purpose: []
